stages:
  - build<% if(includeTests && includeFunctions) { %>
  - unit_tests<% } %>
  - deploy_staging<% if(includeTests) { %>
  - e2e_tests<% } %>
  - build_production
  - deploy_production

# Cache dependencies across jobs only pulling not uploading (upload to cache
# happens in build stage)
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull # only pull cache, skip uploading
  paths:
    - node_modules/<% if(includeFunctions) { %>
    - functions/node_modules/<% } %>

# Install dependencies for React App<% if(includeFunctions) { %> and Cloud Functions<% } %>. <% if(includeTests) { %>Installing of
# cypress binary is skipped (done in E2E Testing Stage)<% } %>
# Script run before all stages unless otherwise overriden
before_script:
  - CYPRESS_INSTALL_BINARY=0 npm i<% if(includeFunctions) { %>
  - npm i --prefix functions<% } %>
  - npm i firebase-tools@6.1.0 firebase-ci@next

# Build Stage
# Installs dependencies, builds app, and saves results for later (artifacts).
# 1. Install dependencies for React App and Cloud Functions. Installing of
# cypress binary is skipped (done in E2E Testing Stage)
# 2. Build environment specific config file in src/config.js
# 3. Confirm there is no lint within code (after config is injected for import linting)
# 4. Build React app to dist folder
# 5. Preserve build results and dependencies for future jobs in the pipeline
Build:
  stage: build
  image: node:8
  when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist
      - functions/dist
  # Override cache behavior set above since we want to both pull and push to
  # the cache (no "policy" provided since pull-push is default)
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - functions/node_modules/
  script:
    - npm run build:config # create env specific src/config.js
    - npm run lint
    - npm run build
    - npm run build:functions

<% if(includeTests && includeFunctions) { %># Unit Testing Stage
# Run unit tests for Cloud Functions
Unit Tests:
  stage: unit_tests
  image: node:8
  when: on_success
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-unit-tests/
  artifacts:
    expire_in: 2 weeks
    paths:
      - functions/dist
      - functions/coverage # Test coverage report
      - functions/mochawesome-report # Test results in JSON and HTML
  before_script:
    - npm i --prefix functions
  script:
    - npm run test:cov --prefix functions

<% } %># Deploy Staging
# Deploy React App and Cloud Functions
Deploy Staging:
  stage: deploy_staging
  image: node:8
  environment:
    name: staging
    url: https://<%= appName %>-stage.firebaseapp.com
  when: on_success
  only:
    - master
    - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-stage-deploy/
  script:
    - npm run deploy

<% if(includeTests) { %># End To End Tests
# Install Cypress binary and run end to end tests using Cypress
E2E Tests:
  stage: e2e_tests
  image: cypress/base
  when: on_success
  allow_failure: true
  only:
    - master
    - web
    - schedules
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-e2e-tests/
  # Override cache behavior set above since we want to both pull and push to
  # the cache (no "policy" provided since pull-push is default)
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .cache/Cypress/
  artifacts:
    expire_in: 2 weeks
    paths:
      - cypress/videos
      - cypress/screenshots
      - cypress.env.json
  # Override before_script behavior set above since we want to install the
  # Cypress Binary
  before_script:
     # Install deps including Cypress binary (skipped in default before_script)
    - npm i
    - npm i cypress
    # Confirm Cypress is ready to use
    - $(npm bin)/cypress verify
  script:
     # Create environment specific test config including auth token
     # (saved to cypress.env.json) then run E2E Tests through Cypress
    - npm run test:stage -- --record --key $CYPRESS_KEY

<% } %># Build Production version of bundle (has different config)
Build Production:
  stage: build_production
  image: node:8
  when: on_success
  only:
    - master
    - prod
    - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-prod-deploy/
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist
  script:
    - npm run clean # remove existing dist folder
    - npm run build:config # create env specific src/config.js
    - npm run build # rebuild bundle with new config
    # Note: Functions are not rebuilt since a bundle with env specific config
    # is not created as with React App

# Deploy Production
# Deploy React App and Cloud Functions to production environment
Deploy Production:
  stage: deploy_production
  image: node:8
  environment:
    name: production
    url: https://<%= appName %>.firebaseapp.com
  when: manual # Only allow run through button on Gitlab site
  only:
    - master
    - prod
    - web
  variables:
    FIREBASE_CI_PROJECT: "prod" # deploy using prod project in .firebaserc
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-prod-deploy/
  script:
    - npm run deploy # Deploy Cloud Functions and React App (Firebase Hosting)
