languages:
  JavaScript: true

exclude_paths:
- "lib/**"
- "test/**"
- "example/**"
- "bin/**"
- "webpack.config.base.js"
- "webpack.config.development.js"
- "webpack.config.production.js"
- "LICENSE"
- "README.md"
- "config.json"
- "package.json"
- "generators/**/templates/**"

engines:
  duplication:
    enabled: true
    exclude_fingerprints:
      # Remove code similarity warnings between generators (similar prompt handler)
    - 68c273c948b53d6a86b5eefa38483332
    - e24148612c25eb0528c05d3f03fb51f7
    - 2f8bfbf9830dc0e0f7128e337a9eb6d3
    - 702835e30de2f6c7f01ee88413ff9ed2
