language: node_js

node_js:
- 6.9.1

sudo: false

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

install:
  - npm set progress=false
  - npm install

script:
  - npm run create-config # create environment specific config.js file
  - npm run lint:fix
  - npm run test
  - npm run build:prod

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  - npm i -g firebase-ci # install firebase-ci
  - firebase-ci deploy
