# For for information on config options, visit docs:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/functions"
    open-pull-requests-limit: 3
    schedule: 
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
