/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see <% if(ciProvider === 'travis') { %>.travis.yml<% } else { %>.gitlab-ci.yaml<% } %>).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'dev'

// Config for firebase
export const firebase = {
  apiKey: '<%= firebaseKey %>',
  authDomain: '<%= firebaseName %>.firebaseapp.com',
  databaseURL: 'https://<%= firebaseName %>.firebaseio.com',
  projectId: '<%= firebaseName %>',
  storageBucket: '<%= firebaseName %>.appspot.com'<% if(messagingSenderId) { %>,
  messagingSenderId: '<%= messagingSenderId %>'<% } %><% if(measurementId) { %>,
  measurementId: '<%= messagingSenderId %>'<% } %><% if(appId) { %>,
  appId: '<%= appId %>'<% } %>
}<% if (includeAnalytics) { %>

export const segmentId = '<%= segmentId %>'<% } %><% if (includeMessaging) { %>

export const publicVapidKey = '<%= firebasePublicVapidKey %>'<% } %><% if (includeErrorHandling) { %>

export const sentryDsn = '<%= sentryDsn %>'<% } %>
