/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'dev'

// Config for firebase
export const firebase = {
  "projectId": "redux-firebasev3",
  "appId": "1:823357791673:web:e53b561c7e36427fe06a68",
  "databaseURL": "https://redux-firebasev3.firebaseio.com",
  "storageBucket": "redux-firebasev3.appspot.com",
  "locationId": "us-central",
  "apiKey": "AIzaSyCTUERDM-Pchn_UDTsfhVPiwM4TtNIxots",
  "authDomain": "redux-firebasev3.firebaseapp.com",
  "messagingSenderId": "823357791673",
  "measurementId": "G-QB2GP30FWW"
}
